cc_library(
    name = "button",
    srcs = [
        "button.cpp",
    ],
    hdrs = [
        "button.h",
    ],
    copts = ["-std=c++17"],
    visibility = ["//visibility:public"],
    deps = [
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-system",
        "@sfmllib//:sfml-window",
    ],
)