cc_library(
    name = "user_lobby",
    srcs = [
        "user_lobby.cpp",
    ],
    hdrs = [
        "user_lobby.h",
    ],
    copts = ["-std=c++17"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/button:button",
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-system",
        "@sfmllib//:sfml-window",
    ],
)
