cc_library(
    name = "chessboard_square",
    srcs = [
        "chessboard_square.cpp",
    ],
    hdrs = [
        "chessboard_square.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//include/pieces:pieces",
        "@sfmllib//:sfml-all",
    ],
)
