cc_library(
    name = "local_base",
    srcs = [
        "local_base.cpp",
    ],
    hdrs = [
        "local_base.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-window",
        "@sfmllib//:sfml-system",
        "@sqllite3//:sqlite3"
    ],
)
