cc_library(
    name = "piece_upgrade",
    srcs = [
        "piece_upgrade.cpp",
    ],
    hdrs = [
        "piece_upgrade.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//include/chessboard:chessboard",
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-window",
        "@sfmllib//:sfml-system",
    ],
)
