cc_library(
    name = "text",
    srcs = [
        "text.cpp",
    ],
    hdrs = [
        "text.h",
    ],
    copts = [
        "-std=c++17",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-system",
        "@sfmllib//:sfml-window",
    ],
)
