cc_library(
    name = "page_lobby",
    srcs = [
        "page_lobby.cpp",
    ],
    hdrs = [
        "page_lobby.h",
    ],
    copts = ["-std=c++17"],
    visibility = ["//visibility:public"],
    deps = [
        "//include/user_lobby:user_lobby",
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-system",
        "@sfmllib//:sfml-window",
    ],
)
