cc_library(
    name = "game",
    srcs = [
        "game.cpp",
    ],
    hdrs = [
        "game.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//include/chessboard:chessboard",
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-window",
        "@sfmllib//:sfml-system",
    ],
)
