cc_library(
    name = "start_menu",
    srcs = [
        "start_menu.cpp",
    ],
    hdrs = [
        "start_menu.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//include/chessboard:chessboard",
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-window",
        "@sfmllib//:sfml-system",
    ],
)
