cc_library(
    name = "main_menu",
    srcs = [
        "main_menu.cpp",
    ],
    hdrs = [
        "main_menu.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//include/start_menu:start_menu",
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-window",
        "@sfmllib//:sfml-system",
    ],
)
