cc_library(
    name = "chessboard",
    srcs = [
        "chessboard.cpp",
    ],
    hdrs = [
        "chessboard.h",
    ],
    visibility = ["//visibility:public"],
    # data = [
    #     "//include/512h:png-files",
    # ],
    deps = [
        "//include/chessboard_square:chessboard_square",
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-window",
        "@sfmllib//:sfml-system",
        # "@sfmllib//:sfml-all",
    ],
)
