cc_library(
    name = "chessboard",
    srcs = [
        "chessboard.cpp",
    ],
    hdrs = [
        "chessboard.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//include/chessboard_square:chessboard_square",
        "@sfmllib//:sfml-all",
    ],
)
