cc_library(
    name = "pieces",
    srcs = [
        "pieces.cpp",
    ],
    hdrs = [
        "pieces.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        # "//include/main_menu:main_menu",
        "@sfmllib//:sfml-graphics",
        "@sfmllib//:sfml-window",
        "@sfmllib//:sfml-system",
    ],
)
