cc_library(
    name = "pieces",
    srcs = [
        "pieces.cpp",
    ],
    hdrs = [
        "pieces.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@sfmllib//:sfml-all",
    ],
)
